Revert "Don't randomly re-define a bunch of standard things."
Bill Paul kindly figured out what this stuff does:

> I think I just answered my own question when testing out your patch.
> The
> underlying problem again is using the host-based ELF code with the
> target-
> based type definitions.
>
> The elf.h file includes other files. Both on Linux and FreeBSD,
> /usr/include/elf.h will end up including stdint.h. If you build
> *without*
> using -stc=c99 or -std=c11, then efibind.h defines its own versions of
> the
> various types (uint64_t, int64_t, etc..). And when you do that, you
> get a
> conflict:
>
> /usr/bin/gcc -I./../gnuefi -I./../gnuefi/../inc
> -I./../gnuefi/../inc/x86_64 -
> I./../gnuefi/../inc/protocol   -O2 -fpic -Wall -fshort-wchar
> -fno-strict-
> aliasing -fno-merge-constants -mno-red-zone -DCONFIG_x86_64 -c
> reloc_x86_64.c
> -o reloc_x86_64.o
> In file included from ./../gnuefi/../inc/efi.h:35,
>                  from reloc_x86_64.c:43:
> ./../gnuefi/../inc/x86_64/efibind.h:58: error: conflicting types for
> 'uint64_t'
> /usr/include/stdint.h:56: note: previous declaration of 'uint64_t' was
> here
> ./../gnuefi/../inc/x86_64/efibind.h:59: error: conflicting types for
> 'int64_t'
> /usr/include/stdint.h:41: note: previous declaration of 'int64_t' was
> here
> ./../gnuefi/../inc/x86_64/efibind.h:65: error: conflicting types for
> 'int8_t'
> /usr/include/stdint.h:37: note: previous declaration of 'int8_t' was
> here
> make[1]: *** [reloc_x86_64.o] Error 1
>
> I get the same conflict on FreeBSD too.
>
> So the reason those #defines are present in reloc_x86_64.c and
> reloc_ia32.c is
> to work around this: they hide the typedefs from stdint.h so that the
> ones in
> elfbind.h won't conflict with them.
>
> If you build with -stc=c99, then elfbind.h falls through to the
> #include
> <stdint.h> case, and then there's no conflict.

This reverts commit a9866f5bcd9642eaea65ee0e73fe6e46f2bd6f9e.